In [37]:
# conjunto de textos
documentos = [
    "gato bebe leite",
    "gato bebe agua",
    "gato come peixe",
    "gato dorme no sofa",
    "gato brinca com novelo",
    "gato mia durante a noite",

    "cachorro bebe agua",
    "cachorro come racao",
    "cachorro corre no quintal",
    "cachorro late para estranho",
    "cachorro brinca com bola",

    "peixe nada no aquario",
    "peixe come racao",
    "peixe nada rapido",
    "aquario possui planta natural",
    "aquario precisa de filtro",

    "passaro canta pela manha",
    "passaro voa alto",
    "passaro come sementes",
    "canario canta bonito",
    "papagaio imita palavras",

    "carro anda na estrada",
    "carro precisa de gasolina",
    "carro tem motor potente",
    "onibus transporta passageiros",
    "moto anda rapido",

    "computador processa dados",
    "computador possui memoria",
    "notebook e portatil",
    "teclado possui teclas",
    "mouse move cursor",

    "banana e fruta amarela",
    "maca e fruta vermelha",
    "laranja tem vitamina c",
    "uva cresce em cachos",
    "abacaxi e fruta tropical",

    "professor ensina matematica",
    "aluno estuda para prova",
    "escola possui biblioteca",
    "universidade oferece cursos",
    "livro contem conhecimento"
]

LSA

In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD

# 1. Converter textos em matriz TF-IDF
vectorizer = TfidfVectorizer()
X_tfidf = vectorizer.fit_transform(documentos)

print("Formato original TF-IDF:")
print(X_tfidf.shape)   # (n_documentos, n_termos)

Formato original TF-IDF:
(41, 94)

Q1) Observe o código abaixo e varie o número de componentes (vetores singulares).
Utilizando a similaridade coseno (https://scikit-learn.org/stable/modules/generated/sklearn.metrics.pairwise.cosine_similarity.html), encontre os documentos mais similares entre si. Os documentos resultantes se alteram?

In [39]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import pandas as pd

componentes = [2,3,5,7,9,11]

resultados = []

for n_componentes in componentes:
    # 2. Aplicar LSA
    lsa = TruncatedSVD(n_components=n_componentes, random_state=42)
    X_reduzido = lsa.fit_transform(X_tfidf)

    m_sim = cosine_similarity(X_reduzido)

    np.fill_diagonal(m_sim, -1)
    i, j = np.unravel_index(np.argmax(m_sim), m_sim.shape)

    resultados.append({
        "componentes" : n_componentes,
        "doc1" : i+1,
        "doc2" : j+1,
        "similaridade" : m_sim[i,j]
    })

df_q1 = pd.DataFrame(resultados)
df_q1

   componentes  doc1  doc2  similaridade
0            2     4    10      0.999998
1            3    28    39      0.999954
2            5    28    39      0.999666
3            7    32    33      0.999934
4            9    32    33      0.999381
5           11    32    36      0.999425

In [40]:
# 3. Coordenadas dos documentos no espaço reduzido
print("\nRepresentação reduzida:")
for i, vetor in enumerate(X_reduzido[:10,:]):
    print(f"Doc {i+1}: {vetor}")

Representação reduzida:
Doc 1: [ 0.42191252  0.5463174   0.12226189 -0.15449542 -0.20407927  0.20112475
 -0.00554288 -0.09333024 -0.00986864 -0.02003916 -0.00789096]
Doc 2: [ 0.5072305   0.69170587  0.11171531 -0.10684451 -0.14379167  0.19694152
  0.00396048 -0.22340614  0.10686363  0.01778524 -0.06041265]
Doc 3: [ 0.75481284 -0.24170503 -0.03303837 -0.14780456 -0.22783153  0.10177253
 -0.00769175  0.00467699 -0.22486363 -0.09309729  0.02588219]
Doc 4: [ 0.30409285  0.15765299  0.19832409 -0.17989208 -0.11710634 -0.09228796
  0.00104251  0.30556956  0.03233138 -0.11687421  0.36417879]
Doc 5: [ 0.29487695  0.2971515   0.02553354  0.00863474  0.05837831 -0.13943899
 -0.01550259  0.60900576 -0.4187546   0.06366848 -0.16091631]
Doc 6: [ 0.22049818  0.19881864  0.08259148 -0.14665503 -0.19380749  0.10594788
 -0.01874268  0.21161499 -0.21696563 -0.08250185  0.07647428]
Doc 7: [ 0.44584301  0.59904778 -0.03319474  0.15001726  0.17671756 -0.00565562
  0.01465379 -0.34406587  0.29653639  0.08863642 -0.08859099]
Doc 8: [ 0.59460099 -0.25256316 -0.38582263  0.33818715  0.24904334 -0.05792176
  0.00731247 -0.21326156 -0.11635768 -0.08078104 -0.04005985]
Doc 9: [ 0.24445457  0.06229897  0.02208612  0.14500375  0.29192109 -0.3535458
  0.01213803  0.11304463  0.32044492 -0.01060364  0.31676166]
Doc 10: [ 0.16394897  0.1011385  -0.12996701  0.27669646  0.37249474 -0.26490238
 -0.00083695 -0.08314617  0.24320689  0.09760241  0.08031166]

In [41]:
# LSA para reduzir dimensionalidade de PALAVRAS

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
import pandas as pd

# 1. Matriz termo-documento
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(documentos)

# termos (palavras)
termos = vectorizer.get_feature_names_out()

In [42]:
# 2. Transpor para palavra x documento
# agora cada linha representa uma palavra
X_palavras = X.T

print("Formato original (palavras x documentos):")
print(X_palavras.shape)

Formato original (palavras x documentos):
(94, 41)

Q2) Observe o código abaixo e varie o número de componentes (vetores singulares).
Utilizando a similaridade coseno (https://scikit-learn.org/stable/modules/generated/sklearn.metrics.pairwise.cosine_similarity.html), encontre as palavras mais similares entre si. Os documentos resultantes se alteram?

In [43]:
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import pandas as pd

componentes = [2,3,5,7,9,11]

resultados = []

for n_componentes in componentes:
    # 2. Aplicar LSA
    lsa = TruncatedSVD(n_components=n_componentes, random_state=42)
    X_palavras_reduzido = lsa.fit_transform(X_tfidf)

    m_sim = cosine_similarity(X_palavras_reduzido)

    np.fill_diagonal(m_sim, -1)
    i, j = np.unravel_index(np.argmax(m_sim), m_sim.shape)

    resultados.append({
        "componentes" : n_componentes,
        "doc1" : termos[i],
        "doc2" : termos[j],
        "similaridade" : m_sim[i,j]
    })

df_q2 = pd.DataFrame(resultados)
df_q2

   componentes   doc1        doc2  similaridade
0            2  aluno  biblioteca      0.999998
1            3  dados       fruta      0.999954
2            5  dados       fruta      0.999666
3            7     em      ensina      0.999934
4            9     em      ensina      0.999381
5           11     em    estranho      0.999425

In [44]:
from sklearn.decomposition import TruncatedSVD

# 3. Aplicar LSA para palavras com 2 componentes para visualização
lsa_words = TruncatedSVD(n_components=2, random_state=42)
X_palavras_reduzido_2d = lsa_words.fit_transform(X_palavras)

# 4. Mostrar coordenadas reduzidas das palavras
df = pd.DataFrame(X_palavras_reduzido_2d, columns=["Dim1", "Dim2"])
df["Palavra"] = termos

print("\nVetores reduzidos das palavras:")
print(df[["Palavra", "Dim1", "Dim2"]].sort_values("Palavra"))

Vetores reduzidos das palavras:
         Palavra          Dim1      Dim2
0        abacaxi  2.408309e-04  0.001118
1           agua  3.612389e-01  0.558819
2           alto  2.166507e-02 -0.036332
3          aluno  7.502095e-03 -0.001818
4        amarela  1.270530e-05  0.000322
..           ...           ...       ...
89  universidade  3.632307e-05  0.000556
90           uva -4.233231e-04  0.002719
91      vermelha  8.039643e-05  0.000638
92      vitamina -9.781903e-07 -0.001441
93           voa  2.166507e-02 -0.036332

[94 rows x 3 columns]

Word2Vec

In [45]:
!pip install gensim

Requirement already satisfied: gensim in /usr/local/lib/python3.12/dist-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.6.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.2)

Q3) Altere o código abaixo para inicializar  avariável frases com os documentos anteriores tokenizados. Varie o tamanho da janela e do vetor no Word2Vec. Mostre como diferentes tamanhos podem alterar os resultados das palavras mais similares.

In [46]:
from gensim.models import Word2Vec
import pandas as pd

frases = [doc.split() for doc in documentos]
frases

configuracoes = [
    {"vector_size" : 8, "window" : 2},
    {"vector_size" : 8, "window" : 4},
    {"vector_size" : 20, "window" : 2},
    {"vector_size" : 20, "window" : 4}
]

results = []

for config in configuracoes:
  modelo = Word2Vec(
      sentences=frases,
      vector_size=config["vector_size"],
      window=config["window"],
      min_count=1,
      epochs = 200,
      sg = 1,
      workers = 1,
      seed = 42
  )

  similars = modelo.wv.most_similar("gato", topn=5)

  results.append({
      "vector_size" : config["vector_size"],
      "window" : config["window"],
      "gato" : similars
      })

  df_q3 = pd.DataFrame(results)
  print(df_q3)

   vector_size  window                                               gato
0            8       2  [(aluno, 0.9359959959983826), (canta, 0.932467...
   vector_size  window                                               gato
0            8       2  [(aluno, 0.9359959959983826), (canta, 0.932467...
1            8       4  [(aluno, 0.9597063660621643), (canta, 0.935524...
   vector_size  window                                               gato
0            8       2  [(aluno, 0.9359959959983826), (canta, 0.932467...
1            8       4  [(aluno, 0.9597063660621643), (canta, 0.935524...
2           20       2  [(uva, 0.8208296895027161), (fruta, 0.81963294...
   vector_size  window                                               gato
0            8       2  [(aluno, 0.9359959959983826), (canta, 0.932467...
1            8       4  [(aluno, 0.9597063660621643), (canta, 0.935524...
2           20       2  [(uva, 0.8208296895027161), (fruta, 0.81963294...
3           20       4  [(fruta, 0.8753884434700012), (uva, 0.87161576...

FastText

Q4) Varie o tamanho da janela e do vetor no FastText. Mostre como diferentes tamanhos podem alterar os resultados das palavras mais similares. Compare os resultados com aqueles obtidos pelo Word2Vec.

In [47]:
from gensim.models import FastText
# Treinando modelo FastText
modelo = FastText(
    sentences=frases,
    vector_size=20,
    window=2,
    min_count=1,
    workers=1,
    sg=1              # Skip-Gram
)

# Vetor da palavra "gato"
print("Vetor de gato:")
print(modelo.wv["gato"])

Vetor de gato:
[ 0.00191586 -0.00063885  0.00817206  0.01139614 -0.00103864 -0.0219687
 -0.00039271 -0.00597942  0.01346882 -0.00248693  0.00968654  0.00921908
 -0.00757199  0.00269917  0.01724596 -0.00694008  0.00301676  0.00408407
  0.0148315  -0.00485238]

In [48]:
# Palavras mais similares
print("\nMais similares a gato:")
print(modelo.wv.most_similar("gato"))

Mais similares a gato:
[('canario', 0.4871898293495178), ('laranja', 0.4252546727657318), ('maca', 0.3848838806152344), ('planta', 0.3667268455028534), ('anda', 0.3533434271812439), ('com', 0.3520452380180359), ('moto', 0.34802478551864624), ('cachos', 0.34768912196159363), ('alto', 0.3461574614048004), ('motor', 0.327200323343277)]

Q5) Teste outras palavras fora do vocabulário e veja quais palavras o FastText retorna como mais similares.

In [49]:

# Palavra não vista no treino
palavras_teste = ["gatinho", "cachorrinho", "computadorzinho", "casinha"]

for palavra in palavras_teste:
    print("\nPalavra testada:", palavra)
    print("Palavras mais similares:")

    similares = modelo.wv.most_similar(palavra, topn=5)

    for termo, score in similares:
        print(f"{termo} - {score:.4f}")

Palavra testada: gatinho
Palavras mais similares:
passaro - 0.6813
pela - 0.6098
para - 0.5414
racao - 0.4717
cursos - 0.4298

Palavra testada: cachorrinho
Palavras mais similares:
cachorro - 0.5622
cursos - 0.5225
corre - 0.4966
passaro - 0.4204
natural - 0.4159

Palavra testada: computadorzinho
Palavras mais similares:
computador - 0.8461
abacaxi - 0.4581
manha - 0.3959
com - 0.3929
teclado - 0.3837

Palavra testada: casinha
Palavras mais similares:
nada - 0.6149
move - 0.5472
portatil - 0.4603
palavras - 0.4600
manha - 0.4436

Q6)O código abaixo utiliza Embeddings treinados em um corpora maior. Faça testes de analogias e similaridades com diferentes palavras no idioma do modelo. Reporte os resultados do Word2Vec e do FastText separadamente.

Word2Vec pré-treinado

In [50]:
import gensim.downloader as api

# Baixar/carregar modelo pré-treinado pequeno
# (vetores de 25 dimensões treinados no Twitter)
modelo = api.load("word2vec-google-news-300")

[==================================================] 100.0% 1662.8/1662.8MB downloaded

In [51]:

# Vetor da palavra
print("Vetor de 'king':")
print(modelo["king"])

Vetor de 'king':
[ 1.25976562e-01  2.97851562e-02  8.60595703e-03  1.39648438e-01
 -2.56347656e-02 -3.61328125e-02  1.11816406e-01 -1.98242188e-01
  5.12695312e-02  3.63281250e-01 -2.42187500e-01 -3.02734375e-01
 -1.77734375e-01 -2.49023438e-02 -1.67968750e-01 -1.69921875e-01
  3.46679688e-02  5.21850586e-03  4.63867188e-02  1.28906250e-01
  1.36718750e-01  1.12792969e-01  5.95703125e-02  1.36718750e-01
  1.01074219e-01 -1.76757812e-01 -2.51953125e-01  5.98144531e-02
  3.41796875e-01 -3.11279297e-02  1.04492188e-01  6.17675781e-02
  1.24511719e-01  4.00390625e-01 -3.22265625e-01  8.39843750e-02
  3.90625000e-02  5.85937500e-03  7.03125000e-02  1.72851562e-01
  1.38671875e-01 -2.31445312e-01  2.83203125e-01  1.42578125e-01
  3.41796875e-01 -2.39257812e-02 -1.09863281e-01  3.32031250e-02
 -5.46875000e-02  1.53198242e-02 -1.62109375e-01  1.58203125e-01
 -2.59765625e-01  2.01416016e-02 -1.63085938e-01  1.35803223e-03
 -1.44531250e-01 -5.68847656e-02  4.29687500e-02 -2.46582031e-02
  1.85546875e-01  4.47265625e-01  9.58251953e-03  1.31835938e-01
  9.86328125e-02 -1.85546875e-01 -1.00097656e-01 -1.33789062e-01
 -1.25000000e-01  2.83203125e-01  1.23046875e-01  5.32226562e-02
 -1.77734375e-01  8.59375000e-02 -2.18505859e-02  2.05078125e-02
 -1.39648438e-01  2.51464844e-02  1.38671875e-01 -1.05468750e-01
  1.38671875e-01  8.88671875e-02 -7.51953125e-02 -2.13623047e-02
  1.72851562e-01  4.63867188e-02 -2.65625000e-01  8.91113281e-03
  1.49414062e-01  3.78417969e-02  2.38281250e-01 -1.24511719e-01
 -2.17773438e-01 -1.81640625e-01  2.97851562e-02  5.71289062e-02
 -2.89306641e-02  1.24511719e-02  9.66796875e-02 -2.31445312e-01
  5.81054688e-02  6.68945312e-02  7.08007812e-02 -3.08593750e-01
 -2.14843750e-01  1.45507812e-01 -4.27734375e-01 -9.39941406e-03
  1.54296875e-01 -7.66601562e-02  2.89062500e-01  2.77343750e-01
 -4.86373901e-04 -1.36718750e-01  3.24218750e-01 -2.46093750e-01
 -3.03649902e-03 -2.11914062e-01  1.25000000e-01  2.69531250e-01
  2.04101562e-01  8.25195312e-02 -2.01171875e-01 -1.60156250e-01
 -3.78417969e-02 -1.20117188e-01  1.15234375e-01 -4.10156250e-02
 -3.95507812e-02 -8.98437500e-02  6.34765625e-03  2.03125000e-01
  1.86523438e-01  2.73437500e-01  6.29882812e-02  1.41601562e-01
 -9.81445312e-02  1.38671875e-01  1.82617188e-01  1.73828125e-01
  1.73828125e-01 -2.37304688e-01  1.78710938e-01  6.34765625e-02
  2.36328125e-01 -2.08984375e-01  8.74023438e-02 -1.66015625e-01
 -7.91015625e-02  2.43164062e-01 -8.88671875e-02  1.26953125e-01
 -2.16796875e-01 -1.73828125e-01 -3.59375000e-01 -8.25195312e-02
 -6.49414062e-02  5.07812500e-02  1.35742188e-01 -7.47070312e-02
 -1.64062500e-01  1.15356445e-02  4.45312500e-01 -2.15820312e-01
 -1.11328125e-01 -1.92382812e-01  1.70898438e-01 -1.25000000e-01
  2.65502930e-03  1.92382812e-01 -1.74804688e-01  1.39648438e-01
  2.92968750e-01  1.13281250e-01  5.95703125e-02 -6.39648438e-02
  9.96093750e-02 -2.72216797e-02  1.96533203e-02  4.27246094e-02
 -2.46093750e-01  6.39648438e-02 -2.25585938e-01 -1.68945312e-01
  2.89916992e-03  8.20312500e-02  3.41796875e-01  4.32128906e-02
  1.32812500e-01  1.42578125e-01  7.61718750e-02  5.98144531e-02
 -1.19140625e-01  2.74658203e-03 -6.29882812e-02 -2.72216797e-02
 -4.82177734e-03 -8.20312500e-02 -2.49023438e-02 -4.00390625e-01
 -1.06933594e-01  4.24804688e-02  7.76367188e-02 -1.16699219e-01
  7.37304688e-02 -9.22851562e-02  1.07910156e-01  1.58203125e-01
  4.24804688e-02  1.26953125e-01  3.61328125e-02  2.67578125e-01
 -1.01074219e-01 -3.02734375e-01 -5.76171875e-02  5.05371094e-02
  5.26428223e-04 -2.07031250e-01 -1.38671875e-01 -8.97216797e-03
 -2.78320312e-02 -1.41601562e-01  2.07031250e-01 -1.58203125e-01
  1.27929688e-01  1.49414062e-01 -2.24609375e-02 -8.44726562e-02
  1.22558594e-01  2.15820312e-01 -2.13867188e-01 -3.12500000e-01
 -3.73046875e-01  4.08935547e-03  1.07421875e-01  1.06933594e-01
  7.32421875e-02  8.97216797e-03 -3.88183594e-02 -1.29882812e-01
  1.49414062e-01 -2.14843750e-01 -1.83868408e-03  9.91210938e-02
  1.57226562e-01 -1.14257812e-01 -2.05078125e-01  9.91210938e-02
  3.69140625e-01 -1.97265625e-01  3.54003906e-02  1.09375000e-01
  1.31835938e-01  1.66992188e-01  2.35351562e-01  1.04980469e-01
 -4.96093750e-01 -1.64062500e-01 -1.56250000e-01 -5.22460938e-02
  1.03027344e-01  2.43164062e-01 -1.88476562e-01  5.07812500e-02
 -9.37500000e-02 -6.68945312e-02  2.27050781e-02  7.61718750e-02
  2.89062500e-01  3.10546875e-01 -5.37109375e-02  2.28515625e-01
  2.51464844e-02  6.78710938e-02 -1.21093750e-01 -2.15820312e-01
 -2.73437500e-01 -3.07617188e-02 -3.37890625e-01  1.53320312e-01
  2.33398438e-01 -2.08007812e-01  3.73046875e-01  8.20312500e-02
  2.51953125e-01 -7.61718750e-02 -4.66308594e-02 -2.23388672e-02
  2.99072266e-02 -5.93261719e-02 -4.66918945e-03 -2.44140625e-01
 -2.09960938e-01 -2.87109375e-01 -4.54101562e-02 -1.77734375e-01
 -2.79296875e-01 -8.59375000e-02  9.13085938e-02  2.51953125e-01]

In [52]:

# Palavras mais similares
print("\nMais similares a 'king':")
print(modelo.most_similar("king", topn=5))

# Similaridade entre palavras
print("\nSimilaridade king x queen:")
print(modelo.similarity("king", "queen"))

Mais similares a 'king':
[('kings', 0.7138045430183411), ('queen', 0.6510956883430481), ('monarch', 0.6413194537162781), ('crown_prince', 0.6204220056533813), ('prince', 0.6159993410110474)]

Similaridade king x queen:
0.6510957

In [53]:

# Analogia:
# king - man + woman ≈ queen
print("\nAnalogia king - man + woman:")
print(modelo.most_similar(
    positive=["king", "woman"],
    negative=["man"],
    topn=5
))

Analogia king - man + woman:
[('queen', 0.7118193507194519), ('monarch', 0.6189674139022827), ('princess', 0.5902431011199951), ('crown_prince', 0.5499460697174072), ('prince', 0.5377321839332581)]

FastText pre-treinado

In [54]:
!pip install fasttext

Requirement already satisfied: fasttext in /usr/local/lib/python3.12/dist-packages (0.9.3)
Requirement already satisfied: pybind11>=2.2 in /usr/local/lib/python3.12/dist-packages (from fasttext) (3.0.4)
Requirement already satisfied: setuptools>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from fasttext) (75.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from fasttext) (2.0.2)

In [55]:
 ! wget https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.pt.300.bin.gz

--2026-05-01 17:49:52--  https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.pt.300.bin.gz
Resolving dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)... 13.249.182.81, 13.249.182.62, 13.249.182.33, ...
Connecting to dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)|13.249.182.81|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4505096760 (4.2G) [application/octet-stream]
Saving to: ‘cc.pt.300.bin.gz’

cc.pt.300.bin.gz    100%[===================>]   4.20G  63.8MB/s    in 49s

2026-05-01 17:50:41 (87.2 MB/s) - ‘cc.pt.300.bin.gz’ saved [4505096760/4505096760]

In [56]:
!gunzip /content/cc.pt.300.bin.gz

gzip: /content/cc.pt.300.bin already exists; do you wish to overwrite (y or n)? y

In [57]:
import fasttext

# Carregar modelo pré-treinado em português
modelo = fasttext.load_model("/content/cc.pt.300.bin")

# Vetor da palavra
print("Vetor de gato:")
print(modelo.get_word_vector("gato")[:10])

# Palavra similar (via vizinhos mais próximos)
print("\nPalavras próximas de gato:")
print(modelo.get_nearest_neighbors("gato", k=5))

# Similaridade manual
import numpy as np

v1 = modelo.get_word_vector("gato")
v2 = modelo.get_word_vector("cachorro")

similaridade = np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))

print("\nSimilaridade gato x cachorro:")
print(similaridade)

# Palavra nunca vista (vantagem do FastText)
print("\nPalavra nova:")
print(modelo.get_word_vector("gatinhozinho")[:10])

Vetor de gato:
[ 0.09164401  0.03087921  0.07897757  0.01735242  0.0456139  -0.10999835
  0.01344797 -0.02422255 -0.03451584 -0.08393902]

Palavras próximas de gato:
[(0.8184635043144226, 'gatinho'), (0.7903094291687012, 'cão'), (0.7688173055648804, 'cachorro'), (0.7447839379310608, 'gatoO'), (0.7386516332626343, 'felino')]

Similaridade gato x cachorro:
0.76881766

Palavra nova:
[-0.02883657  0.02422135  0.00560624 -0.00548069  0.00861132 -0.0724509
  0.00091006 -0.00310351 -0.00605459 -0.04560084]

In [58]:
palavras_teste = ["gato", "cachorro", "computador", "gatinho"]

for palavra in palavras_teste:
    print("\nPalavra:", palavra)

    similares = modelo.get_nearest_neighbors(palavra, k=5)

    for score, termo in similares:
        print(f"{termo} ({score:.4f})")

Palavra: gato
gatinho (0.8185)
cão (0.7903)
cachorro (0.7688)
gatoO (0.7448)
felino (0.7387)

Palavra: cachorro
cão (0.8647)
cachorrinho (0.8203)
cãozinho (0.8168)
cahorro (0.7711)
gato (0.7688)

Palavra: computador
ocomputador (0.7467)
microcomputador (0.7279)
laptop (0.7261)
umcomputador (0.7080)
docomputador (0.7043)

Palavra: gatinho
gato (0.8185)
cachorrinho (0.7899)
cãozinho (0.7593)
gatinha (0.7301)
filhotinho (0.7138)